apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scanner-metrics
  namespace: hawk
  labels:
    app.kubernetes.io/name: arc-hawk-dd
    app.kubernetes.io/component: scanner
    app.kubernetes.io/part-of: arc-hawk-dd
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: arc-hawk-dd
      app.kubernetes.io/component: scanner
  namespaceSelector:
    matchNames:
      - hawk
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
