apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-scan-default-scaler
  namespace: hawk
  labels:
    app.kubernetes.io/name: arc-hawk-dd
    app.kubernetes.io/component: celery-worker-scan-default
spec:
  scaleTargetRef:
    name: celery-worker-scan-default
  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 2
  maxReplicaCount: 20
  triggers:
    - type: redis
      metadata:
        address: redis.hawk.svc.cluster.local:6379
        listName: scan_default
        listLength: "50"
        activationListLength: "1"
