ALTER TABLE audit_logs
DROP COLUMN IF EXISTS tenant_id,
DROP COLUMN IF EXISTS user_id,
DROP COLUMN IF EXISTS action,
DROP COLUMN IF EXISTS resource_type,
DROP COLUMN IF EXISTS resource_id,
DROP COLUMN IF EXISTS ip_address,
DROP COLUMN IF EXISTS user_agent,
DROP COLUMN IF EXISTS metadata;
