package service

import (
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/arc-platform/backend/modules/shared/domain/entity"
	"github.com/arc-platform/backend/modules/shared/scoring"
	"github.com/google/uuid"
)

// VerifiedFinding represents SDK-validated finding from the Go scanner.
// Schema aligns with the Go scanner ingest API (apps/goScanner).
type VerifiedFinding struct {
	PIIType   string `json:"pii_type"`
	ValueHash string `json:"value_hash"`
	// MatchedValue is the raw substring the pattern fired on (e.g. the email
	// itself). This is what gets displayed as the finding's evidence. The
	// scanner is the authoritative source for this field; older payloads
	// without it fall back to ContextExcerpt at ingest time.
	MatchedValue     string         `json:"matched_value"`
	Source           SourceLocation `json:"source"`
	ValidatorsPassed []string       `json:"validators_passed"`
	ValidationMethod string         `json:"validation_method"`
	MLConfidence     float64        `json:"ml_confidence"`
	MLEntityType     string         `json:"ml_entity_type"`
	ContextExcerpt   string         `json:"context_excerpt"`
	ContextKeywords  []string       `json:"context_keywords"`
	PatternName      string         `json:"pattern_name"`
	DetectedAt       string         `json:"detected_at"`
	SDKVersion       string         `json:"scanner_version"`
	Metadata         map[string]any `json:"metadata,omitempty"`
}

// EvidenceValue returns the finding's raw matched value (preferred) or falls
// back to the context excerpt for legacy payloads that did not include a
// matched_value field. Use this wherever you need "the thing the pattern
// matched on" — for UI display, value hashing, and format validation.
func (vf *VerifiedFinding) EvidenceValue() string {
	if vf.MatchedValue != "" {
		return vf.MatchedValue
	}
	return vf.ContextExcerpt
}

// SourceLocation represents source information from the Go scanner.
// Corresponds to the SourceInfo struct in the Go scanner API (apps/goScanner).
type SourceLocation struct {
	Path       string `json:"path"`
	Line       int    `json:"line,omitempty"`
	Column     string `json:"column,omitempty"`
	Table      string `json:"table,omitempty"`
	DataSource string `json:"data_source"` // filesystem, postgresql, mysql
	Host       string `json:"host"`
}

// SDKAdapter maps SDK findings to existing entity structures
type SDKAdapter struct{}

func NewSDKAdapter() *SDKAdapter {
	return &SDKAdapter{}
}

// MapToAsset creates an Asset entity from SDK finding
func (a *SDKAdapter) MapToAsset(vf *VerifiedFinding) *entity.Asset {
	cleanHost := extractCleanHost(vf.Source.Host, vf.Source.DataSource)
	name := vf.Source.Path
	if name == "" {
		name = assetDisplayName(vf.Source.DataSource, cleanHost, vf.Source.Host)
	}
	// Note: StableID will be generated by AssetService
	return &entity.Asset{
		ID:           uuid.New(),
		StableID:     "", // Will be generated by AssetService
		AssetType:    vf.Source.DataSource,
		Name:         name,
		Path:         vf.Source.Path,
		DataSource:   vf.Source.DataSource,
		Host:         cleanHost,
		Environment:  "production",
		Owner:        "",
		SourceSystem: "arc-hawk-scanner",
		FileMetadata: map[string]any{
			"sdk_version":    vf.SDKVersion,
			"scan_timestamp": time.Now().Unix(),
		},
		RiskScore:     0,
		TotalFindings: 0,
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
	}
}

// extractCleanHost sanitizes a potentially DSN-style host string to just host[:port].
// PostgreSQL DSNs look like: user=x password=y dbname=z host=hostname port=1234
func extractCleanHost(raw, dataSource string) string {
	if raw == "" {
		return raw
	}
	// DSN key=value style (postgresql, mysql)
	if strings.Contains(raw, "host=") {
		hostRe := regexp.MustCompile(`host=(\S+)`)
		portRe := regexp.MustCompile(`port=(\d+)`)
		hm := hostRe.FindStringSubmatch(raw)
		pm := portRe.FindStringSubmatch(raw)
		if len(hm) > 1 {
			if len(pm) > 1 {
				return hm[1] + ":" + pm[1]
			}
			return hm[1]
		}
	}
	// Already a plain hostname or mongodb+srv URI
	return raw
}

// assetDisplayName builds a human-readable name for database/cloud assets.
func assetDisplayName(dataSource, cleanHost, rawHost string) string {
	switch dataSource {
	case "postgresql", "mysql":
		// Try to extract dbname from DSN
		dbRe := regexp.MustCompile(`dbname=(\S+)`)
		if m := dbRe.FindStringSubmatch(rawHost); len(m) > 1 {
			return fmt.Sprintf("%s/%s", cleanHost, m[1])
		}
		return cleanHost
	case "mongodb":
		// Strip shard suffix: ac-xxx-shard-00-01.cluster.net -> cluster.net
		parts := strings.SplitN(cleanHost, ".", 2)
		if len(parts) == 2 {
			return parts[1] // e.g. fxhqpoo.mongodb.net
		}
		return cleanHost
	default:
		return cleanHost
	}
}

// MapToFinding creates a Finding entity from SDK finding
func (a *SDKAdapter) MapToFinding(vf *VerifiedFinding, scanRunID, assetID uuid.UUID) *entity.Finding {
	severity := determineSeverity(vf.PIIType)
	riskScore := int(scoring.ComputeRiskScore(scoring.RiskScoreParams{
		PIIType:        vf.PIIType,
		Confidence:     vf.MLConfidence,
		PIIDensity:     1.0, // single-finding context; density unknown at this point
		AccessExposure: 0.5, // default internal; enriched later when asset accessibility is known
	}))

	evidence := vf.EvidenceValue()
	return &entity.Finding{
		ID:                  uuid.New(),
		ScanRunID:           scanRunID,
		AssetID:             assetID,
		PatternID:           nil,
		PatternName:         vf.PatternName,
		Matches:             []string{evidence},
		SampleText:          evidence,
		Severity:            severity,
		SeverityDescription: getSeverityDescription(severity),
		RiskScore:           riskScore,
		ConfidenceScore:     floatPtr(vf.MLConfidence),
		Context: map[string]any{
			"keywords":    vf.ContextKeywords,
			"excerpt":     vf.ContextExcerpt,
			"line":        vf.Source.Line,
			"column":      vf.Source.Column,
			"table":       vf.Source.Table,
			"data_source": vf.Source.DataSource,
			"host":        vf.Source.Host,
		},
		EnrichmentSignals: map[string]any{
			"validators_passed": vf.ValidatorsPassed,
			"validation_method": vf.ValidationMethod,
			"ml_entity_type":    vf.MLEntityType,
			"sdk_validated":     true,
			"sdk_version":       vf.SDKVersion,
		},
		EnrichmentScore:  floatPtr(1.0),
		EnrichmentFailed: false,
		CreatedAt:        time.Now(),
		UpdatedAt:        time.Now(),
	}
}

// MapToClassification creates a Classification entity from SDK finding
// CRITICAL CONTRACT: SubCategory MUST equal vf.PIIType for lineage aggregation
// Semantic lineage service relies on SubCategory to create PII_Category nodes in Neo4j graph
func (a *SDKAdapter) MapToClassification(vf *VerifiedFinding, findingID uuid.UUID) *entity.Classification {
	classificationType := mapPIITypeToClassification(vf.PIIType)
	dpdpaCategory := getDPDPACategory(vf.PIIType)

	// Confidence scoring: boost MLConfidence for SDK-validated findings that passed format validators
	mlConf := vf.MLConfidence
	if len(vf.ValidatorsPassed) > 0 && mlConf < 0.85 {
		mlConf = 0.85 // Format-validated findings deserve high base confidence
	}
	finalScore := 0.6*mlConf + 0.25*calculateContextScore(vf.ContextKeywords) + 0.15*1.0

	return &entity.Classification{
		ID:                 uuid.New(),
		FindingID:          findingID,
		ClassificationType: classificationType,
		SubCategory:        vf.PIIType, // CRITICAL: Must be PII type for lineage (IN_AADHAAR, CREDIT_CARD, etc.)
		ConfidenceScore:    finalScore,
		Justification:      generateJustification(vf),
		DPDPACategory:      dpdpaCategory,
		RequiresConsent:    requiresConsent(vf.PIIType),
		RetentionPeriod:    getRetentionPeriod(vf.PIIType),
		SignalBreakdown: map[string]any{
			"rule_signal": map[string]any{
				"confidence":     0.0,
				"weight":         0.0,
				"weighted_score": 0.0,
			},
			"presidio_signal": map[string]any{
				"confidence":     vf.MLConfidence,
				"weight":         0.6,
				"weighted_score": 0.6 * vf.MLConfidence,
				"explanation":    "SDK-validated with " + joinStrings(vf.ValidatorsPassed),
			},
			"context_signal": map[string]any{
				"confidence":     calculateContextScore(vf.ContextKeywords),
				"weight":         0.25,
				"weighted_score": 0.25 * calculateContextScore(vf.ContextKeywords),
			},
			"entropy_signal": map[string]any{
				"confidence":     0.0,
				"weight":         0.0,
				"weighted_score": 0.0,
			},
		},
		EngineVersion: "sdk-v" + vf.SDKVersion,
		RuleScore:     floatPtr(0.0),
		PresidioScore: floatPtr(vf.MLConfidence),
		ContextScore:  floatPtr(calculateContextScore(vf.ContextKeywords)),
		EntropyScore:  floatPtr(0.0),
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
	}
}

// Helper functions - using existing generateStableID from ingestion_service.go

func determineSeverity(piiType string) string {
	// Only India PIIs + Credit Card in scope (Intelligence-at-Edge)
	criticalTypes := []string{"IN_AADHAAR", "IN_PAN", "CREDIT_CARD", "IN_PASSPORT"}
	for _, ct := range criticalTypes {
		if piiType == ct {
			return "Critical"
		}
	}
	return "High"
}

func getSeverityDescription(severity string) string {
	descriptions := map[string]string{
		"Critical": "Contains sensitive personal identifiers requiring immediate attention",
		"High":     "Contains personal data requiring protection",
		"Medium":   "Contains potentially sensitive information",
		"Low":      "Contains general information",
	}
	return descriptions[severity]
}

func mapPIITypeToClassification(piiType string) string {
	// Only India PIIs in scope (11 locked types)
	mapping := map[string]string{
		"IN_AADHAAR":         "Sensitive Personal Data",
		"IN_PAN":             "Sensitive Personal Data",
		"IN_PASSPORT":        "Sensitive Personal Data",
		"CREDIT_CARD":        "Financial Data",
		"IN_UPI":             "Financial Data",
		"IN_IFSC":            "Financial Data",
		"IN_BANK_ACCOUNT":    "Financial Data",
		"IN_PHONE":           "Personal Data",
		"EMAIL_ADDRESS":      "Personal Data",
		"IN_VOTER_ID":        "Government Identifier",
		"IN_DRIVING_LICENSE": "Government Identifier",
	}
	if ct, ok := mapping[piiType]; ok {
		return ct
	}
	return "Personal Data"
}

func getDPDPACategory(piiType string) string {
	// DPDPA 2023 categories for India PIIs only
	mapping := map[string]string{
		"IN_AADHAAR":         "Sensitive Personal Data",
		"IN_PAN":             "Financial Identifier",
		"IN_PASSPORT":        "Government Identifier",
		"CREDIT_CARD":        "Financial Data",
		"IN_UPI":             "Financial Identifier",
		"IN_IFSC":            "Financial Identifier",
		"IN_BANK_ACCOUNT":    "Financial Data",
		"IN_PHONE":           "Contact Information",
		"EMAIL_ADDRESS":      "Contact Information",
		"IN_VOTER_ID":        "Government Identifier",
		"IN_DRIVING_LICENSE": "Government Identifier",
	}
	if cat, ok := mapping[piiType]; ok {
		return cat
	}
	return "General Personal Data"
}

func requiresConsent(piiType string) bool {
	// India DPDPA 2023: Sensitive data requiring explicit consent
	sensitiveTypes := []string{"IN_AADHAAR", "IN_PAN", "IN_PASSPORT", "CREDIT_CARD", "IN_DRIVING_LICENSE"}
	for _, st := range sensitiveTypes {
		if piiType == st {
			return true
		}
	}
	return false
}

func getRetentionPeriod(piiType string) string {
	if requiresConsent(piiType) {
		return "7 years (financial/tax compliance)"
	}
	return "3 years (general data retention)"
}

func calculateContextScore(keywords []string) float64 {
	if len(keywords) == 0 {
		return 0.0
	}
	// Simple heuristic: more keywords = higher confidence
	score := float64(len(keywords)) * 0.1
	if score > 1.0 {
		score = 1.0
	}
	return score
}

func generateJustification(vf *VerifiedFinding) string {
	validators := joinStrings(vf.ValidatorsPassed)
	if validators == "" {
		validators = "pattern matching"
	}
	return "SDK-validated " + vf.PIIType + " using " + validators + " (confidence: " + formatFloat(vf.MLConfidence*100) + "%)"
}

func joinStrings(strs []string) string {
	if len(strs) == 0 {
		return ""
	}
	result := strs[0]
	for i := 1; i < len(strs); i++ {
		result += ", " + strs[i]
	}
	return result
}

func formatFloat(f float64) string {
	return fmt.Sprintf("%.2f", f)
}

func floatPtr(f float64) *float64 {
	return &f
}
