{{- if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arc-hawk-dd.fullname" . }}-frontend
  labels:
    {{- include "arc-hawk-dd.labels" . | nindent 4 }}
    {{- include "arc-hawk-dd.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "arc-hawk-dd.selectorLabels" (dict "root" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arc-hawk-dd.selectorLabels" (dict "root" . "component" "frontend") | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ include "arc-hawk-dd.image" (dict "root" . "repo" .Values.frontend.image.repository "tag" .Values.frontend.image.tag) }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            {{- range $k, $v := .Values.frontend.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources: {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe: {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels: {{- include "arc-hawk-dd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "arc-hawk-dd.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      name: http
{{- end }}
