"""
India Identity Patterns
========================
PII patterns for Indian government-issued identity documents.

Covered:
  IN_AADHAAR           Aadhaar UID (12-digit)
  IN_AADHAAR_VID       Virtual Aadhaar ID (16-digit)
  IN_PAN               Permanent Account Number
  IN_PASSPORT          Indian Passport Number (improved)
  IN_VOTER_ID          Voter ID / EPIC (improved)
  IN_DRIVING_LICENSE   Driving Licence (improved)
  IN_RATION_CARD       Ration Card Number
  IN_NPS_PRAN          National Pension System PRAN
  IN_UAN               Universal Account Number (EPFO)
  IN_ESIC              Employee State Insurance Corporation number
  IN_DIN               Director Identification Number
  IN_ABHA              Ayushman Bharat Health Account ID
"""

import re
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from patterns.base import PiiPattern, PatternCategory, DPDPASchedule


# --------------------------------------------------------------------------- #
# Validators imported lazily to avoid circular imports at module load time     #
# --------------------------------------------------------------------------- #

def _validate_aadhaar(value: str) -> bool:
    """Verhoeff checksum + first-digit check."""
    from validators.verhoeff import validate_aadhaar
    return validate_aadhaar(value)


def _validate_pan(value: str) -> bool:
    """PAN format + entity-type check."""
    from validators.pan import validate_pan
    return validate_pan(value)


def _validate_passport(value: str) -> bool:
    """
    Indian passport: [A-PR-WY][1-9][0-9]{5}[1-9][A-Za-z]
    Rejects letters Q, X, Z in first position (not issued).
    """
    clean = re.sub(r"[^A-Za-z0-9]", "", value).upper()
    if len(clean) != 9:
        return False
    if clean[0] in ('Q', 'X', 'Z'):
        return False
    if not re.match(r"^[A-PR-WY][1-9][0-9]{5}[1-9][A-Z]$", clean):
        return False
    return True


# --------------------------------------------------------------------------- #
# Pattern definitions                                                          #
# --------------------------------------------------------------------------- #

IN_AADHAAR = PiiPattern(
    id="IN_AADHAAR",
    name="Aadhaar Number",
    category=PatternCategory.INDIA_IDENTITY,
    dpdpa_schedule=DPDPASchedule.SENSITIVE_PERSONAL_DATA,
    patterns=[
        # 12-digit, first digit 2-9, allows single space/hyphen separators
        r"(?<!\d)[2-9]\d{3}[\s-]?\d{4}[\s-]?\d{4}(?!\d)",
    ],
    confidence_base=0.9,
    sensitivity="critical",
    context_keywords=[
        "aadhaar", "aadhar", "uid", "uidai",
        "unique identification", "unique identity", "enrollment", "enrolment",
    ],
    validator=_validate_aadhaar,
    description="12-digit UIDAI-issued unique identification number with Verhoeff checksum.",
    false_positive_risk="low",
    example="2345 6789 0126",
    country="IN",
    is_locked=True,
)

IN_AADHAAR_VID = PiiPattern(
    id="IN_AADHAAR_VID",
    name="Virtual Aadhaar ID (VID)",
    category=PatternCategory.INDIA_IDENTITY,
    dpdpa_schedule=DPDPASchedule.SENSITIVE_PERSONAL_DATA,
    patterns=[
        # 16-digit starting with 9 (UIDAI VID spec) — no leading/trailing digit
        r"(?<!\d)9\d{3}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}(?!\d)",
    ],
    confidence_base=0.6,
    sensitivity="critical",
    context_keywords=[
        "vid", "virtual_id", "virtual_aadhaar", "masked_aadhaar",
        "virtual id", "masked aadhaar",
    ],
    validator=None,  # No public checksum algorithm for VID
    description="16-digit virtual ID generated by UIDAI for privacy-preserving Aadhaar usage.",
    false_positive_risk="high",
    example="9876 1234 5678 9012",
    country="IN",
    is_locked=False,
)

IN_PAN = PiiPattern(
    id="IN_PAN",
    name="Permanent Account Number (PAN)",
    category=PatternCategory.INDIA_IDENTITY,
    dpdpa_schedule=DPDPASchedule.SENSITIVE_PERSONAL_DATA,
    patterns=[
        # 5 alpha + 4 digits + 1 alpha, whole-word boundary
        r"(?i)\b[A-Z]{5}[0-9]{4}[A-Z]\b",
    ],
    confidence_base=0.9,
    sensitivity="critical",
    context_keywords=[
        "pan", "pancard", "pan card", "permanent account",
        "income tax", "tax id", "tax number",
    ],
    validator=_validate_pan,
    description="10-character alphanumeric tax identifier issued by India's Income Tax Department.",
    false_positive_risk="low",
    example="ABCDE1234F",
    country="IN",
    is_locked=True,
)

IN_PASSPORT = PiiPattern(
    id="IN_PASSPORT",
    name="Indian Passport Number",
    category=PatternCategory.INDIA_IDENTITY,
    dpdpa_schedule=DPDPASchedule.SENSITIVE_PERSONAL_DATA,
    patterns=[
        # Improved: excludes Q/X/Z first letter; format [A-PR-WY][1-9][0-9]{5}[1-9][A-Z]
        r"(?i)\b[A-PR-WYa-pr-wy][1-9][0-9]{5}[1-9][A-Za-z]\b",
    ],
    confidence_base=0.75,
    sensitivity="critical",
    context_keywords=[
        "passport", "passport_no", "passport_number", "pp_no",
        "travel_document", "travel document", "ppno",
    ],
    validator=_validate_passport,
    description="9-character Indian passport number issued by MEA (Ministry of External Affairs).",
    false_positive_risk="medium",
    example="A1234567B",
    country="IN",
    is_locked=True,
)

IN_VOTER_ID = PiiPattern(
    id="IN_VOTER_ID",
    name="Voter ID / EPIC",
    category=PatternCategory.INDIA_IDENTITY,
    dpdpa_schedule=DPDPASchedule.SENSITIVE_PERSONAL_DATA,
    patterns=[
        # 3 uppercase alpha + 7 digits — strict uppercase to reduce FP
        r"\b[A-Z]{3}[0-9]{7}\b",
    ],
    confidence_base=0.5,
    sensitivity="high",
    context_keywords=[
        "voter_id", "voter id", "epic", "election", "voter_card",
        "electors", "ec_id",
    ],
    validator=None,
    description="Electors Photo Identity Card (EPIC) number issued by the Election Commission of India.",
    false_positive_risk="high",
    example="ABC1234567",
    country="IN",
    is_locked=True,
)

IN_DRIVING_LICENSE = PiiPattern(
    id="IN_DRIVING_LICENSE",
    name="Indian Driving Licence",
    category=PatternCategory.INDIA_IDENTITY,
    dpdpa_schedule=DPDPASchedule.SENSITIVE_PERSONAL_DATA,
    patterns=[
        # Format: 2-letter state code + 2-digit RTO + 4-digit year + 7-digit serial
        r"(?i)\b[A-Z]{2}[\s-]?[0-9]{2}[\s-]?[0-9]{4}[\s-]?[0-9]{7}\b",
        # Compact form (no separators, 15 digits after 2 alpha)
        r"(?i)\b[A-Z]{2}[0-9]{13}\b",
    ],
    confidence_base=0.6,
    sensitivity="high",
    context_keywords=[
        "driving_license", "driving_licence", "dl_no", "dl_number",
        "license_number", "licence_number", "dl",
    ],
    validator=None,
    description="Indian driving licence number issued by state RTOs; format varies by state.",
    false_positive_risk="medium",
    example="MH-12-2019-1234567",
    country="IN",
    is_locked=True,
)

IN_RATION_CARD = PiiPattern(
    id="IN_RATION_CARD",
    name="Ration Card Number",
    category=PatternCategory.INDIA_IDENTITY,
    dpdpa_schedule=DPDPASchedule.PERSONAL_DATA,
    patterns=[
        # State prefix (2-3 alpha) + 8-10 digits, optional separator
        r"(?i)\b[A-Z]{2,3}[\s-]?[0-9]{8,10}\b",
    ],
    confidence_base=0.5,
    sensitivity="medium",
    context_keywords=[
        "ration_card", "ration_no", "ration card", "pds",
        "fair_price", "food_security",
    ],
    validator=None,
    description="State-issued ration card number used under the Public Distribution System (PDS).",
    false_positive_risk="high",
    example="MH12345678",
    country="IN",
    is_locked=False,
)

IN_NPS_PRAN = PiiPattern(
    id="IN_NPS_PRAN",
    name="NPS Permanent Retirement Account Number (PRAN)",
    category=PatternCategory.INDIA_IDENTITY,
    dpdpa_schedule=DPDPASchedule.SENSITIVE_PERSONAL_DATA,
    patterns=[
        # 12-digit number starting with 1 (PFRDA spec)
        r"(?<!\d)1[0-9]{11}(?!\d)",
    ],
    confidence_base=0.65,
    sensitivity="high",
    context_keywords=[
        "pran", "nps", "pension", "retirement_account",
        "national_pension", "pfrda",
    ],
    validator=None,
    description="12-digit Permanent Retirement Account Number issued by PFRDA for NPS subscribers.",
    false_positive_risk="high",
    example="110045678901",
    country="IN",
    is_locked=False,
)

IN_UAN = PiiPattern(
    id="IN_UAN",
    name="Universal Account Number (UAN) — EPFO",
    category=PatternCategory.INDIA_IDENTITY,
    dpdpa_schedule=DPDPASchedule.PERSONAL_DATA,
    patterns=[
        # 12-digit number — very broad, must rely on context
        r"(?<!\d)[0-9]{12}(?!\d)",
    ],
    confidence_base=0.2,
    sensitivity="medium",
    context_keywords=[
        "uan", "epf", "provident_fund", "pf_account",
        "employee_provident", "epfo",
    ],
    validator=None,
    description="12-digit Universal Account Number issued by EPFO for Employees' Provident Fund.",
    false_positive_risk="critical",
    example="100123456789",
    country="IN",
    is_locked=False,
)

IN_ESIC = PiiPattern(
    id="IN_ESIC",
    name="Employee State Insurance (ESIC) Number",
    category=PatternCategory.INDIA_IDENTITY,
    dpdpa_schedule=DPDPASchedule.PERSONAL_DATA,
    patterns=[
        # 17-digit number — requires context to avoid FP
        r"(?<!\d)[0-9]{17}(?!\d)",
    ],
    confidence_base=0.65,
    sensitivity="medium",
    context_keywords=[
        "esic", "employee_insurance", "esi_no", "esi_number",
        "employee_state_insurance",
    ],
    validator=None,
    description="17-digit insurance number issued by ESIC (Employees' State Insurance Corporation).",
    false_positive_risk="high",
    example="12345678901234567",
    country="IN",
    is_locked=False,
)

IN_DIN = PiiPattern(
    id="IN_DIN",
    name="Director Identification Number (DIN)",
    category=PatternCategory.INDIA_CORPORATE,
    dpdpa_schedule=DPDPASchedule.PERSONAL_DATA,
    patterns=[
        # 8-digit number; very broad without context
        r"(?<!\d)[0-9]{8}(?!\d)",
    ],
    confidence_base=0.6,
    sensitivity="medium",
    context_keywords=[
        "din", "director_identification", "mca", "director_id",
        "din_number",
    ],
    validator=None,
    description="8-digit Director Identification Number issued by MCA for company directors.",
    false_positive_risk="critical",
    example="00123456",
    country="IN",
    is_locked=False,
)

IN_ABHA = PiiPattern(
    id="IN_ABHA",
    name="Ayushman Bharat Health Account (ABHA) ID",
    category=PatternCategory.INDIA_HEALTHCARE,
    dpdpa_schedule=DPDPASchedule.SENSITIVE_PERSONAL_DATA,
    patterns=[
        # 14-digit, displayed as XX-XXXX-XXXX-XXXX
        r"(?<!\d)[0-9]{2}[\s-]?[0-9]{4}[\s-]?[0-9]{4}[\s-]?[0-9]{4}(?!\d)",
        # Compact 14 digits
        r"(?<!\d)[0-9]{14}(?!\d)",
    ],
    confidence_base=0.75,
    sensitivity="critical",
    context_keywords=[
        "abha", "health_id", "ayushman", "health_account",
        "ndhm", "health_id_number",
    ],
    validator=None,
    description="14-digit Ayushman Bharat Health Account identifier issued by NHA under ABDM.",
    false_positive_risk="medium",
    example="91-2345-6789-0123",
    country="IN",
    is_locked=False,
)


# Exported list for registry consumption
INDIA_IDENTITY_PATTERNS = [
    IN_AADHAAR,
    IN_AADHAAR_VID,
    IN_PAN,
    IN_PASSPORT,
    IN_VOTER_ID,
    IN_DRIVING_LICENSE,
    IN_RATION_CARD,
    IN_NPS_PRAN,
    IN_UAN,
    IN_ESIC,
    IN_DIN,
    IN_ABHA,
]
