apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-backend
  namespace: hawk
  labels:
    app.kubernetes.io/name: arc-hawk-dd
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: arc-hawk-dd
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: arc-hawk-dd
      app.kubernetes.io/component: backend
