-- 000001_initial_schema.down.sql
-- Reverse the initial schema creation.

BEGIN;

DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS remediation_issues CASCADE;
DROP TABLE IF EXISTS risk_scores CASCADE;
DROP TABLE IF EXISTS findings_2026_06 CASCADE;
DROP TABLE IF EXISTS findings_2026_05 CASCADE;
DROP TABLE IF EXISTS findings_2026_04 CASCADE;
DROP TABLE IF EXISTS findings_2026_03 CASCADE;
DROP TABLE IF EXISTS findings_2026_02 CASCADE;
DROP TABLE IF EXISTS findings_2026_01 CASCADE;
DROP TABLE IF EXISTS findings CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS scan_jobs CASCADE;
DROP TABLE IF EXISTS sources CASCADE;
DROP TABLE IF EXISTS schema_migrations CASCADE;

COMMIT;
